ViewComponents/ViewComponents/Models/Person.cs
namespace ViewComponents.Models
{
    public class Person
    {
        public string? PersonName { get; set; }
        public string? JobTitle { get; set; }
    }
}

ViewComponents/ViewComponents/Models/PersonGridModel.cs
namespace ViewComponents.Models
{
    public class PersonGridModel
    {
        public string GridTitle { get; set; }
        = string.Empty;

        public List<Person> Persons { get; set;} = new List<Person>();
    }
}

ViewComponents/ViewComponents/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using ViewComponents.Models;

namespace ViewComponents.Controllers
{
    public class HomeController : Controller
    {
        [Route("/")]
        public IActionResult Index()
        {
            return View();
        }

        [Route("/about")]
        public IActionResult About()
        {
            return View();
        }

        [Route("friends-list")]
        public IActionResult LoadFriendList()
        {
                PersonGridModel personGridModel = new PersonGridModel()
                {
                    GridTitle = "Friends",
                    Persons = new List<Person>()
                    {
                        new Person() {PersonName = "Mia", JobTitle ="UI designer"},
                        new Person() {PersonName = "Lee", JobTitle ="UX designer"},
                        new Person() {PersonName = "William", JobTitle ="QA"},
                    }
                };
            return ViewComponent("Grid", new {grid = personGridModel});
        }
    }
}

ViewComponents/ViewComponents/ViewComponents/GridViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using ViewComponents.Models;

namespace ViewComponents.ViewComponents
{
    public class GridViewComponent : ViewComponent
    {
         public async Task<IViewComponentResult> InvokeAsync(PersonGridModel grid )
        {
            return View("Sample", grid); //invoked a partiel view // a defualt route => Views/Shared/Grid/Default.cshtml
        }
    }
}

ViewComponents/ViewComponents/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}

<h1>About</h1>
<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry.
    Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,
    when an unknown printer took a galley of type and scrambled it to make a type
    specimen book. It has survived not only five centuries, but also the leap into
    electronic typesetting, remaining essentially unchanged. It was popularised in 
    the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, 
    and more recently with desktop publishing software like Aldus PageMaker including 
    versions of Lorem Ipsum.</p>

@{
    PersonGridModel personGridModel = new PersonGridModel()
            {
                GridTitle = "Employees",
                Persons = new List<Person>()
                    {
                        new Person() {PersonName = "Clark", JobTitle ="data scientist"},
                        new Person() {PersonName = "Kevin", JobTitle ="UX designer"},
                        new Person() {PersonName = "Varun", JobTitle ="QA"},
                    }
            };
}
@await Component.InvokeAsync("Grid", new { 
        grid = personGridModel
})

    @await Component.InvokeAsync("Grid")

    <vc:grid grid="personGridModel"></vc:grid>

ViewComponents/ViewComponents/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home";
}
<h1>Home</h1>

<button class="button blue-back" id="load-friends-button">Load Friends</button>

<div id="list">

</div>

<script src="~/friends.js"></script>

ViewComponents/ViewComponents/Views/Shared/Components/Grid/Sample.cshtml
@model PersonGridModel

<div class="box">
    <h3>@Model.GridTitle</h3>
    <table class="table w-100">
        <thead>
            <tr>
                <th>Sl. No</th>
                <th>Name</th>
            </tr>
        </thead>
        <tbody>
            @foreach(Person person in Model.Persons)
            {
             <tr>
                <td>@person.PersonName</td>
                <td>@person.JobTitle</td>
            </tr>  
            }    
        </tbody>
    </table>
</div>

ViewComponents/ViewComponents/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/StyleSheet.css" rel="stylesheet" />
</head>
<body>
     <div class="container">
         <div class="navbar">
             <div class="navbar-brand">View Components Demo App</div>
         <ul>
             <li><a href="~/">Home</a></li>
             <li><a href="~/about">About</a></li>
         </ul>
     </div>
     <div class="page-content">
         @RenderBody()
     </div>
</body>
</html>